import doubly_list

print("---Add Before After---")
dllist = doubly_list.DoublyLinkedList()
dllist.prepend(0)
dllist.append(1)
dllist.append(2)
dllist.append(3)
dllist.append(4)
dllist.prepend(5)
dllist.print_list()
print("Add after node 3")
dllist.add_after_node(3,6)
dllist.print_list()
print("Add before node 4")
dllist.add_before_node(4,9)
dllist.print_list()